[package]
name = "akumuli-rs"
version = "0.1.0"
authors = ["Ashley <ashley.ruglys@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
akumuli-sys = { path = "akumuli-sys"}
log = "0.4"
